### ISSUE TITLE
No feedback on navigation timeout

### ISSUE THREAD

**Issue by brianlow** [NielsSteensma/Dhalang#24]
Steps to reproduce
```ruby
> res = Dhalang::PDF.get_from_url("https://www.google.com", navigation_timeout: 1);
Navigation timeout of 1 ms exceeded

> res
=> ""
```

I expected a Ruby exception to be raised. Something like `DhalangException.new("Navigation timeout of 1 ms exceeded")`

Is this reasonable? Open to PR?

**Comment by NielsSteensma** [comment]
Hi.

This does seem reasonable indeed. 
Thank you for creating a PR for it. I will check/merge it during the weekend
