### ISSUE TITLE
Error when using long header/footer HTMLs

### ISSUE THREAD

**Issue by piloos** [NielsSteensma/Dhalang#43]
When using long header/footer HTML strings (eg. with base64 encoded images in it) you can run into the limitations of the OS since the Dhalang gem is passing those strings as arguments in its `node` command.  On Linux the maximum length of an argument is 128kB (https://serverfault.com/questions/163371/linux-command-line-character-limit/163390).

Therefore I propose to allow passing the headers/footers by file as well.  See PR #44.

**Comment by NielsSteensma** [comment]
Merged and released ( V0.6.3 )
