### ISSUE TITLE
DhalangError: waiting for Page.printToPDF failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by raphox** [NielsSteensma/Dhalang#47]
In the system I'm working with, we have a PDF with several pages. PDF generation takes more than 30000ms. I think it would be interesting to be able to configure this in the project.

I believe that changes are very similar to https://github.com/NielsSteensma/Dhalang/commit/0ecc0a07d28eb3f4d6516a9b3e4043d2bbd31402

**Comment by NielsSteensma** [comment]
Agreed, seems useful.

Anyone, feel free to assign yourself the issue and open a PR for it.
( If I got some spare time I can also look into it ofc )
