### ISSUE TITLE
Dhalang::PDF.get_from_url results in error 'The "path" argument must be of type string. Received undefined'

### ISSUE THREAD

**Issue by lhobbs22** [NielsSteensma/Dhalang#49]
Calling the `Dhalang::PDF.get_from_url` method causes the following error

`The "path" argument must be of type string. Received undefined`

Where the argument passed is of type string with the http prefix included

This error occurs on version Dhalang version '0.3.0' as well as the current version

Do you know how to fix this issue?

**Comment by NielsSteensma** [comment]
This issue was introduced by 0.3.0 and solved in 0.3.1.
The latest version (0.6.3), for me, works fine. Neither any tests are failing, they should fail if the issue was still present.

Therefore I suspect somehow you still might be on 0.3.0 instead of the latest.
